# Generated by Django 5.0.1 on 2024-01-21 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TradingObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название объекта торговой сети')),
                ('type_trading_object', models.IntegerField(choices=[(0, 'Factory'), (1, 'Retail chain'), (2, 'Individual entrepreneur')], verbose_name='Тип торгового объекта')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Электронная почта объекта торговой сети')),
                ('country', models.CharField(max_length=150, verbose_name='Страна объекта торговой сети')),
                ('city', models.CharField(max_length=150, verbose_name='Город объекта торговой сети')),
                ('street', models.CharField(max_length=150, verbose_name='Улица объекта торговой сети')),
                ('house_number', models.CharField(max_length=20, verbose_name='Номер дома объекта торговой сети')),
                ('dept', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Задолженность перед поставщиком')),
                ('created_at', models.TimeField(auto_now_add=True, verbose_name='Время создания объекта торговой сети')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='trading_object.tradingobject', verbose_name='Поставщик')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название продукта')),
                ('model', models.CharField(max_length=150, verbose_name='Модель продукта')),
                ('release_date', models.DateField(auto_now_add=True, verbose_name='Дата выхода на рынок')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='trading_object.tradingobject', verbose_name='Продавец')),
            ],
        ),
    ]
